### ISSUE TITLE
Split walkthrough document

### ISSUE THREAD

**Issue by jburel** [ome/omero-guides#1]
Currently splitting the long walkthrough into several documents.
This is currently done as g.doc. The file will then be converted into ``.rst`` files
g.docs are under OME Team > Training > General walkthroughs
- [x] Fiji workflow @jburel @pwalczysko (now 4 docs)
- [x] Matlab workflow @jburel
- [x] trackmate workflow @jburel 
- [x] import workflow @pwalczysko (now 3 docs)
- [x] cellprofiler workflow @jburel
- [x] ilastik workflow @pwalczysko 
- [x] core concepts workflow @pwalczysko (now 5 docs)
  - [x] Data management
  - [x] Annotate
  - [x] Search
  - [x] OMERO.iviewer
  - [x] OMERO.FPBioimage
- [x] figure workflow @will-moore 
- [x] parade workflow @will-moore 
- [x] Java API workflow @jburel
- [x] R workflow @jburel @pwalczysko 
- [x] orbit workflow @pwalczysko 
- [x] IExport and download @pwalczysko  (includes OMERO.downloader)
- [x]  Server-side scripts @pwalczysko (to go in Python API)
- [x]  Python API @will-moore

**Comment by jburel** [comment]
idea is to then have a repo per component
e.g. ``omero-doc-cellprofiler-integration``
proposed name to come

**Comment by jburel** [comment]
proposed name for repo:
 * omero-doc-xxx-interaction where xxx can be cellprofiler, ilastik, fiji, trackmate, orbit
 * omero-doc-xxx-api-usage where xxx can be matlab, R, Java, Python
 * omero-doc-core-concepts
 * omero-doc-xxx-usage where xxx can be figure, parade, downloader or a cli plugin

**Comment by will-moore** [comment]
What's wrong with:
omero-doc-ilastik, omero-doc-figure, omero-doc-core, omero-doc-downloader, omero-doc-python etc?

That's a lot easier to remember and what's the difference between 'usage' and 'interaction'? What if an app has both, or changes from one to the other?

**Comment by jburel** [comment]
Those are suggestions. For external software, I went for something more explicit
as we have seen there is already confusion in the community between ``imagej-omero`` and ``omero.imagej``

**Comment by joshmoore** [comment]
A caveat with `omero-doc-$product` is that then it is unclear if this is the code doc or the user guide. _Mea culpa_ for suggesting the shorter `omero-doc-*` prefix but if we want to keep the rest of the name as short as possible, I'd probably go with `omero-guide-*`.

**Comment by pwalczysko** [comment]
@will-moore @jburel removing "iviewer" from the list - "iviewer" is part of "OMERO viewers" already

**Comment by pwalczysko** [comment]
And fpbioimage too

**Comment by pwalczysko** [comment]
Um, and "OMERO viewers" is a result of a split from "Core concenpts" -> to clarify :)

**Comment by pwalczysko** [comment]
Added it to the header (as Core concepts is not self-explaining) - see 
![Screen Shot 2019-08-15 at 15 45 13](https://user-images.githubusercontent.com/2478303/63102787-b0ced500-bf73-11e9-9e05-16441a4574bd.png)

**Comment by jburel** [comment]
name proposal adjustment:
  * omero-guide-xxx where xxx can be cellprofiler, ilastik, fiji, trackmate, orbit
 * omero-guide-xxx-api where xxx can be MATLAB, R, Java, Python
 * omero-doc-core-concepts
 * omero-guide-xxx where xxx can be figure, parade, downloader, iviewer etc. or a cli plugin

**Comment by joshmoore** [comment]
:+1:. For `omero-doc-core-concepts`, perhaps `omero-guide-introduction` ? or will there perhaps be one of those as well, separately?

**Comment by jburel** [comment]
sorry I forgot to change  it, it should have been ``omero-guide-core-concepts``

**Comment by jburel** [comment]
``introduction`` sounds good too.

**Comment by will-moore** [comment]
Yes, I think that 'introduction' is best. And ```omero-guide-xxx[-api]``` sounds good too.

**Comment by jburel** [comment]
It seems that we have reached an agreement. I will create the first repo and take it from there

**Comment by jburel** [comment]
initial work 
 * https://omero-guides.readthedocs.io/en/latest/
 * https://github.com/jburel/omero-guide-cellprofiler
 * https://github.com/jburel/omero-guides
 * https://omero-guide-cellprofiler.readthedocs.io/en/latest/cellprofiler.html

**Comment by jburel** [comment]
downside with the "overarching" doc using the submodule. The functionality "Edit on GitHub" does not work correctly in that case

**Comment by jburel** [comment]
* Decision is to go with split repo
* Make each repo doc "self-contained"
* Offer Training packages at omero-guides level (later) 1h/ 0.5 day/ 1 day etc.

**Comment by jburel** [comment]
After looking at more example I can imagine the following:
* repo ``omero-guide-cp`` (name might be changed) could have doc and content from https://github.com/jburel/integration-cellprofiler. (similar for ilastik, orbit)
* guide for apps like figure, parade, iviewer could be added to the corresponding omero-app repo.
* Python API usage to omero-py, Java to gateway etc.

omero-guides will aggregate the various docs and the ones without repo e.g. omero-intro will go directly in omero-guides
Will that approach be too confusing for people?

comments welcome

**Comment by jburel** [comment]
subproject did not work as I hoping so I have to use submodule

**Comment by pwalczysko** [comment]
@jburel I have added (transferred the repos to you) iviewer and FPBioimage. I checked these in the header of this PR. But I unchecked the other 3 items in "Core concepts" as these are only in the g.doc stage, and the "Image export" too. Still a bit confused about what we will do with the g.doc -> github transfer of these four ? Do we just go the same way as iviewer and FPBioimage ?

**Comment by jburel** [comment]
suggestion for the remaining doc:
* repo name: omero-guide-upload
   * import docs (4)
* omero-guide-download
   * download using script
   * export as
   * downloader
* omero-guide-introduction
   * manage data
   * search
   * browse
   * annotate
*  omero-guide-administrate
  * manage user/group

**Comment by will-moore** [comment]
- omero-guide-admin is a bit nicer than omero-guide-administrate
- could import docs go into introduction? I know some of the import docs can be more advanced, but it seems that intro should have some import docs since you need to import to get started.

**Comment by pwalczysko** [comment]
> could import docs go into introduction? I know some of the import docs can be more advanced, but it seems that intro should have some import docs since you need to import to get started.

Maybe rather a link from the omero-guide-introduction ? Possibly rather a high-level blurb ?

**Comment by jburel** [comment]
Closing this PR 
now we will tackle the migration of help.o.org
