### ISSUE TITLE
copyright statement misleading

### ISSUE THREAD

**Issue by haesleinhuepf** [ome/omero-guides#283]
Hi @jburel et al,

I was just collecting information about licenses of training materials and here in this repository I was a little bit confused. In the github repository exists a [BSD 2 license file](https://github.com/ome/omero-guides/blob/master/LICENSE.md) but on the bottom of the [rendered page](https://omero-guides.readthedocs.io/en/latest/) it says:

![image](https://github.com/ome/omero-guides/assets/12660498/ac029ac1-055f-454f-bdad-d203a7a83700)

Would it be possible to show the right license in the rendered website? That way it would be easier to **R**euse the materials following the FAIR principles.

Thanks!

best,
Robert

**Comment by jburel** [comment]
This is generated by Read the Docs.
We will have to investigate

**Comment by haesleinhuepf** [comment]
Thanks for looking into this! It may just require a chance of this line:
https://github.com/ome/omero-guides/blob/fa12490235a4a5f9849982f579f9d6aa58782fe6/conf.py#L54

Best,
Robert
