### ISSUE TITLE
CLI import - no ssh

### ISSUE THREAD

**Issue by will-moore** [ome/omero-guides#3]
Improve instructions at https://omero-guides.readthedocs.io/en/latest/upload/docs/import-cli.html

Regular CLI import (not in-place) should not connect via ssh to the server or use images from ```/in-place-import/``` directory.

The 'connect via ssh' instructions should be moved down since the in-place import section starts with "We are still in the omero server directory:"

**Comment by pwalczysko** [comment]
proposed fix in https://github.com/ome/omero-guide-upload/pull/9

**Comment by pwalczysko** [comment]
Fix merged.
