### ISSUE TITLE
Logos appear squashed on Safari

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-guides#6]
see: https://omero-guides.readthedocs.io/en/latest/api_usage.html
![Screen Shot 2020-05-12 at 11 44 27](https://user-images.githubusercontent.com/88113/81669088-f5759700-9445-11ea-98ab-483351c10c2e.png)

**Comment by jburel** [comment]
I noticed the problem too, Not only on safari. I will try to sort things out
thanks

**Comment by joshmoore** [comment]
Heh. Ok. Then I'm not going crazy. I just re-opened the page with a different window size and it was normal, so I was going to close the issue. Haven't re-created the situation yet.

**Comment by pwalczysko** [comment]
cannot repeat on my Safari

**Comment by jburel** [comment]
I have opened a PR
https://github.com/ome/omero-guides/pull/7
Screenshot in PR

**Comment by joshmoore** [comment]
cc: @lunson in case she has any ideas.

**Comment by lunson** [comment]
@joshmoore Try applying fixed dimensions to the `td` cell that contains the logo. For example, `<td style="width:100px; height:100px;">[ img of logo here ]</td>`

**Comment by joshmoore** [comment]
Thanks.

**Comment by jburel** [comment]
it is sphinx not html but I will try something like that

**Comment by jburel** [comment]
PR has been merged
